### ISSUE TITLE
ImageChunkMut needs bounds on its Send and Sync traits

### ISSUE THREAD

**Issue by ammaraskar** [Devolutions/gfwx-rs#7]
Hi there, we (Rust group @sslab-gatech) are scanning crates on crates.io for potential soundness bugs. We noticed that ImageChunkMut implements `Send` and `Sync` for all types:

https://github.com/Devolutions/gfwx-rs/blob/59521ca48f635a5a467d73f29bdbb1a6494a455d/src/processing/image.rs#L160-L161

However, this should probably be bound by `T: Send` and `T: Sync` respectively.

I realize this is an image library and the `T` will likely be a numeric type but without these bounds its possible to create data races from safe rust code and cause memory safety issues. Here's a rather contrived example where an "image" is backed by Cells causing a segfault from safe rust code:

```rust
#![forbid(unsafe_code)]

use gfwx::processing::image::Image;

use crossbeam_utils::thread;
use std::cell::Cell;

// A simple tagged union used to demonstrate problems with data races in Cell.
#[derive(Debug, Clone, Copy)]
enum RefOrInt {
    Ref(&'static u64),
    Int(u64),
}
static SOME_INT: u64 = 123;

fn main() {
    let cell = Cell::new(RefOrInt::Ref(&SOME_INT));
    let slice = &mut [&cell];

    let image = Image::from_slice(slice, (1, 1), 1);

    let mut chunk_iterator = image.into_chunks_mut(1, 1);
    let image_chunk = chunk_iterator.next().unwrap();

    thread::scope(|s| {
        s.spawn(|_| {
            let smuggled_cell = image_chunk[(0, 0)];

            loop {
                // Repeatedly write Ref(&addr) and Int(0xdeadbeef) into the cell.
                smuggled_cell.set(RefOrInt::Ref(&SOME_INT));
                smuggled_cell.set(RefOrInt::Int(0xdeadbeef));
            }
        });

        loop {
            if let RefOrInt::Ref(addr) = cell.get() {
                // Hope that between the time we pattern match the object as a
                // `Ref`, it gets written to by the other thread.
                if addr as *const u64 == &SOME_INT as *const u64 { continue; }

                println!("Pointer is now: {:p}", addr);
                println!("Dereferencing addr will now segfault: {}", *addr);
            }
        }
    });
}
```

Output:
```
Pointer is now: 0xdeadbeef

Terminated with signal 11 (SIGSEGV)
```

**Comment by awakecoding** [comment]
@sduquette-devolutions

**Comment by sduquette-devolutions** [comment]
Thank you @ammaraskar for reporting this issue, this is a very nice initiative. This indeed looks like an oversight on our part. I was not able to reproduce a crash with your sample on my system but I created a patch (#8) to only implement Send/Sync on types that are also Send/Sync.
